### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by qbb95** [ssynn/game_translation#2]
test_py3.py的第十五行Lilim.fix_dict()打成Lilim.fix_dixt()了。
还有程序需要安装matplotlib库才能运行，未提醒

**Comment by ssynn** [comment]
感谢提醒，现在基本上已经没时间搞这个了，回头抽时间弄弄吧

**Comment by qbb95** [comment]
没事，我在这里提遇到的问题，大佬有空再改。
在public_function.py的第237行连接data/data.db如果没有创建data文件夹会报错，
第255行conn.commit() 这里会报错AttributeError: 'NoneType' object has no attribute 'commit'，所以我直接注释了。
还有接了百度翻译的接口，提交了个pull requests

**Comment by ssynn** [comment]
extract_gsc应该是后来没改test_py3.py的方法名称。
乱码是因为要改exe文件的CreateFontA的chartset参数，这个参考我在简书上写的yuris汉化攻略吧，原理是一样的
