### ISSUE TITLE
About Lilim

### ISSUE THREAD

**Issue by Sisulizer** [ssynn/game_translation#5]
Is this line [https://github.com/ssynn/game_translation/blob/19d61ed5ad61dd952a55ab4dc2ff95e5a14f337a/src/public_function.py#L3738](url) use for extract text from .scr? I only see the output code.

**Comment by Sisulizer** [comment]
My bad I used AE to extract so it wasn't decrypt but if I use GARbro it is decrypted, but AE can repack .aos, so is there anyway to encrypt the script back?

**Comment by ssynn** [comment]
Text files are not encrypted, they are compressed by **Huffman Coding**, you can try **Lilim.HuffmanDecompressor()** and **Lilim. HuffmanCompressor()**
hope they work

**Comment by Sisulizer** [comment]
I know it's late to ask but is the engine only accept full-width characters?

**Comment by ssynn** [comment]
yes
